# Generated by Django 4.1.1 on 2022-10-05 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='newregister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=130)),
                ('lastname', models.CharField(max_length=130)),
                ('email', models.CharField(max_length=130)),
                ('password1', models.CharField(max_length=130)),
                ('password2', models.CharField(max_length=130)),
                ('date', models.DateField()),
            ],
        ),
    ]
