# Generated by Django 4.1.1 on 2022-10-06 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantapp', '0003_newregister2'),
    ]

    operations = [
        migrations.AddField(
            model_name='newregister2',
            name='username',
            field=models.CharField(default=False, max_length=130),
        ),
    ]
