# Generated by Django 4.1.1 on 2022-10-08 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantapp', '0005_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='textarea',
            field=models.TextField(),
        ),
    ]
